# https://www.home-assistant.io/integrations/default_config/
default_config:

retry:

debugpy:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.retry: debug